const API_URL='https://bitter-recipe-889a.drivehubler10.workers.dev/';
const $=id=>document.getElementById(id);let currentVehicle=null;
function setStatus(message,type=''){ $('status').textContent=message;$('status').className=`status ${type}`; }
function descriptionText(){return $('description').value;}
async function copyDescription(){const text=descriptionText();try{await navigator.clipboard.writeText(text);return true;}catch{const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.focus();ta.select();document.execCommand('copy');ta.remove();return true;}}
function proxyUrl(url){return API_URL+'?action=image&url='+encodeURIComponent(url);}
function renderPhotos(photos=[]){const box=$('photos');box.innerHTML='';photos.forEach((url,i)=>{const item=document.createElement('div');item.className='photo';item.innerHTML=`<img src="${escapeAttr(url)}" alt="Vehicle photo ${i+1}" loading="lazy"><div class="photo-actions"><a href="${escapeAttr(url)}" target="_blank" rel="noopener">Open</a><button type="button" data-download-photo="${i}">Download</button></div>`;box.appendChild(item);item.querySelector('[data-download-photo]').addEventListener('click',()=>downloadOnePhoto(url,i));});$('photoCount').textContent=`${photos.length} photos`;}
async function downloadOnePhoto(url,index){setStatus(`Downloading photo ${index+1}...`);try{const response=await fetch(proxyUrl(url));if(!response.ok)throw new Error();const blob=await response.blob();const objectUrl=URL.createObjectURL(blob);const a=document.createElement('a');a.href=objectUrl;a.download=`vehicle-photo-${String(index+1).padStart(2,'0')}.${extensionFromType(blob.type)}`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(objectUrl),1000);setStatus(`Photo ${index+1} downloaded.`,'ok');}catch{setStatus(`Could not download photo ${index+1}.`,'error');}}
function extensionFromType(type){if(type.includes('png'))return'png';if(type.includes('webp'))return'webp';return'jpg';}
function escapeAttr(s){return String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function fillVehicle(v){currentVehicle=v;$('vehicleHeading').textContent=v.title||'Vehicle';$('vinBadge').textContent=v.vin||'VIN unavailable';$('title').value=v.marketplaceTitle||v.title||'';$('price').value=v.price||'';$('mileage').value=v.mileage||'';$('location').value=v.location||'Indiana';$('stock').value=v.stock||'';$('vin').value=v.vin||'';$('description').value=v.description||'';renderPhotos(v.photos||[]);$('editor').classList.remove('hidden');$('photosCard').classList.remove('hidden');}
async function importVehicle(){const url=$('vehicleUrl').value.trim();if(!url)return setStatus('Paste a DriveHubler vehicle URL first.','error');$('importBtn').disabled=true;setStatus('Importing vehicle information...');try{const res=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const data=await res.json();if(!data.ok)throw new Error(data.error||'Import failed.');fillVehicle(data.vehicle);setStatus('Vehicle imported successfully.','ok');}catch(err){setStatus(err.message||'Failed to fetch the vehicle. Check the Worker URL and deployment.','error');}finally{$('importBtn').disabled=false;}}
$('importBtn').addEventListener('click',importVehicle);$('vehicleUrl').addEventListener('keydown',e=>{if(e.key==='Enter')importVehicle();});$('copyBtn').addEventListener('click',async()=>{await copyDescription();setStatus('Description copied to clipboard.','ok');});$('openMarketplaceBtn').addEventListener('click',async()=>{await copyDescription();setStatus('Description copied. Opening Facebook Marketplace...','ok');window.open('https://www.facebook.com/marketplace/create/vehicle','_blank','noopener');});
$('saveBtn').addEventListener('click',()=>{const saved=JSON.parse(localStorage.getItem('hublerMarketplaceVehicles')||'[]');const record={...currentVehicle,marketplaceTitle:$('title').value,price:$('price').value,mileage:$('mileage').value,location:$('location').value,stock:$('stock').value,vin:$('vin').value,description:$('description').value,savedAt:new Date().toISOString()};const key=record.vin||record.url;const filtered=saved.filter(x=>(x.vin||x.url)!==key);filtered.unshift(record);localStorage.setItem('hublerMarketplaceVehicles',JSON.stringify(filtered.slice(0,100)));renderSaved();setStatus('Vehicle saved in this browser.','ok');});
function renderSaved(){const list=JSON.parse(localStorage.getItem('hublerMarketplaceVehicles')||'[]');$('savedVehicles').innerHTML=list.length?list.map((v,i)=>`<div class="saved-item"><div><strong>${escapeAttr(v.marketplaceTitle||v.title||'Vehicle')}</strong><small>${escapeAttr(v.vin||'')}</small></div><button data-load="${i}">Load</button></div>`).join(''):'<p class="muted">No vehicles saved yet.</p>';list.forEach((_,i)=>document.querySelector(`[data-load="${i}"]`)?.addEventListener('click',()=>fillVehicle(list[i])));}renderSaved();
